Lab2/krechko kirill
lwwwrjke-org/po-4-wt pull request #13
Opened 2021-03-02 14:21 UTC by KrechkoKA

2021-03-02 23:19 UTC, Pavel-Soloduha requested changes

2021-03-02 23:19 UTC, Pavel-Soloduha commented on Reports/lab2/test.html
> +	<script src = "task1.js"> </script>
Введи первым числом - 12 и вторым - 5.

2021-03-02 23:19 UTC, Pavel-Soloduha commented on Reports/lab2/test.html
> +	<script src = "task4.js"> </script>
А 30 февраля это нормально или неочень?

2021-03-02 23:20 UTC, Pavel-Soloduha commented
А и да. У меня есть стойкое подозрение что файлы лежат не совсем там где надо. @lwwwr уточни пожалуйста

2021-03-03 01:36 UTC, lwwwr commented
@Pavel-Soloduha да, иерархия неправильная

2021-03-09 14:38 UTC, closed without merging