Lab1/pivnik nikolay
lwwwrjke-org/po-4-wt pull request #15
Opened 2021-03-02 14:47 UTC by chelseanvp

2021-03-02 23:26 UTC, Pavel-Soloduha requested changes

2021-03-02 23:26 UTC, Pavel-Soloduha commented on Reports/lab1/index.html
> +    <input type="text" name="name" placeholder="Your answer" id="border" required >
А где ограничение на минимальное количество символов?

2021-03-02 23:26 UTC, Pavel-Soloduha commented on Reports/lab1/index.html
> +    <input type="datetyme" name="img_upload" placeholder="Date" id="border"  />
Так какой должен быть календарь? 
datetime или date?

2021-03-14 21:39 UTC, Pavel-Soloduha requested changes

2021-03-14 21:39 UTC, Pavel-Soloduha commented on Reports/lab1/index.html
> +    <input type="text" name="name" placeholder="Your answer" id="border" required  maxlength="50">
Минимальное количество символов, а не максимальное.

2021-03-15 12:58 UTC, chelseanvp commented on Reports/lab1/index.html
> +    <input type="text" name="name" placeholder="Your answer" id="border" required  maxlength="50">
Исправил, теперь точно все окей

2021-03-15 18:08 UTC, closed without merging