Lab2/Mayeski_Aliaksandr
lwwwrjke-org/po-4-wt pull request #21
Opened 2021-03-02 15:14 UTC by GroD-off

2021-03-04 14:27 UTC, Pavel-Soloduha requested changes
Ты ведь понимаешь что у тебя функция ToInt(string) работает скорее всего не так как ты хочешь? Ну или называется некорректно.

2021-03-04 14:27 UTC, Pavel-Soloduha commented on Reports/Mayeski_Aliaksandr/lab2/index.htm
> +    <input type="button" value="TASK 1" onclick="TASK_1()">
Введи 13.1 и 13.2

2021-03-04 21:09 UTC, Pavel-Soloduha approved these changes
В первом задании поменял, а во втором и третьем забил) Ну да ладно. Надеюсь что идею я донёс.

2021-03-15 07:00 UTC, lwwwr submitted a review, later dismissed
почисти конфликты перед мержем лабы

2021-03-16 14:26 UTC, Pavel-Soloduha approved these changes
Где ифы?

2021-03-16 14:37 UTC, merged