lab2/Ivanenko_Ivan : made lab 2
lwwwrjke-org/po-4-wt pull request #25
Opened 2021-03-05 15:34 UTC by vangaru

Lab 2 is ready

2021-03-14 22:11 UTC, Pavel-Soloduha requested changes

2021-03-14 22:11 UTC, Pavel-Soloduha commented on Reports/Ivanenko_Ivan/lab2/task4.js
> +     month == Months.OCTOBER) {
Ничего не смущает, нет?

2021-03-14 22:11 UTC, Pavel-Soloduha commented on Reports/Ivanenko_Ivan/lab2/task3.js
> +function isPositiveNumber(input) {
В порядке общего бреда - функция не выполняет то, как ты её назвал.

2021-03-14 22:11 UTC, Pavel-Soloduha commented on Reports/Ivanenko_Ivan/lab2/task3.js
> +  }else{
Есть подозрение что, что-то пропущено.

2021-03-14 22:11 UTC, Pavel-Soloduha commented on Reports/Ivanenko_Ivan/lab2/task1.js
> +function isNumber(input) {
Объясни пожалуйста зачем эта обёртка над isNaN()?

2021-03-14 23:25 UTC, vangaru commented on Reports/Ivanenko_Ivan/lab2/task4.js
> +     month == Months.OCTOBER) {
Вы про то, что в октябре и ноябре по 29 дней? В задании был указан 2016 год, а он високосный

2021-03-14 23:27 UTC, lwwwr commented on Reports/Ivanenko_Ivan/lab2/task4.js
> +     month == Months.OCTOBER) {
ты вот счас серьезно?

2021-03-14 23:50 UTC, vangaru commented on Reports/Ivanenko_Ivan/lab2/task4.js
> +     month == Months.OCTOBER) {
да..

2021-03-14 23:51 UTC, vangaru commented on Reports/Ivanenko_Ivan/lab2/task4.js
> +     month == Months.OCTOBER) {
В феврале и октябре*

2021-03-15 00:20 UTC, vangaru commented on Reports/Ivanenko_Ivan/lab2/task4.js
> +     month == Months.OCTOBER) {
емае я понял про что вы

2021-03-15 06:58 UTC, lwwwr requested changes

2021-03-15 06:58 UTC, lwwwr commented on Reports/Ivanenko_Ivan/lab2/task4.js
> +     month == Months.OCTOBER) {
месяц октябрь
он что в высокосный, что не в высокосный, всегда имеет 31 день

2021-03-15 07:13 UTC, vangaru commented on Reports/Ivanenko_Ivan/lab2/task4.js
> +     month == Months.OCTOBER) {
Извиняюсь

2021-03-16 15:00 UTC, Pavel-Soloduha approved these changes

2021-03-16 15:02 UTC, Pavel-Soloduha approved these changes

2021-03-16 15:35 UTC, merged