lab1/Galanin_Pavel: pull request (2021.02.23)
lwwwrjke-org/po-4-wt pull request #3
Opened 2021-02-23 05:41 UTC by Pavel-Innokentevich-Galanin

2021-03-02 22:05 UTC, Pavel-Soloduha requested changes

2021-03-02 22:05 UTC, Pavel-Soloduha commented on Reports/Galanin_Pavel/lab1/_myPublicFolder/index.html
> +                    <input class="content__form-input-name" type="text" name="name" value="Your answer" />
Замени value на другую пропертю, чтобы когда вводишь текст не надо было руками очищать поле.

2021-03-02 22:05 UTC, Pavel-Soloduha commented on Reports/Galanin_Pavel/lab1/_myPublicFolder/index.html
> +                    <input class="content__form-input-name" type="text" name="language" value="Your answer"
Тоже самое. Замени value на другую пропертю, чтобы когда вводишь текст не надо было руками очищать поле.
Где ограничение минимальной длины?

2021-03-02 22:49 UTC, Pavel-Innokentevich-Galanin commented on Reports/Galanin_Pavel/lab1/_myPublicFolder/index.html
> +                    <input class="content__form-input-name" type="text" name="name" value="Your answer" />
- Поле руками нужно очищать:
&#60;input name="text" <s>value="Your answer"</s> /&#62;

- Поле руками не надо очищать:
&#60;input name="text" <b>placeholder="Your answer"</b> /&#62;

2021-03-02 22:51 UTC, Pavel-Innokentevich-Galanin commented on Reports/Galanin_Pavel/lab1/_myPublicFolder/index.html
> +                    <input class="content__form-input-name" type="text" name="language" value="Your answer"
- Поле руками нужно очищать:
&#60;input name="text" <s>value="Your answer"</s> /&#62;

- Поле руками не надо очищать:
&#60;input name="text" <b>placeholder="Your answer"</b> /&#62;

---

- Максимальная длина:
&#60;input name="text" <b>maxlength="50"</b> /&#62;

2021-03-02 22:52 UTC, Pavel-Soloduha commented on Reports/Galanin_Pavel/lab1/_myPublicFolder/index.html
> +                    <input class="content__form-input-name" type="text" name="language" value="Your answer"
А чего в коде нету?)
Ну и вроде логичнее всё-таки placeholder чем value?

2021-03-02 23:09 UTC, Pavel-Innokentevich-Galanin commented on Reports/Galanin_Pavel/lab1/_myPublicFolder/index.html
> +                    <input class="content__form-input-name" type="text" name="language" value="Your answer"
Сommit'ы должны появлять ниже этого комментария. Там код обновлен.

2021-03-03 06:22 UTC, Pavel-Soloduha approved these changes

2021-03-04 18:20 UTC, merged