Lab2/Siniak_Danila
lwwwrjke-org/po-4-wt pull request #34
Opened 2021-03-09 18:18 UTC by DanilaSiniak

2021-03-14 23:49 UTC, Pavel-Soloduha requested changes

2021-03-14 23:49 UTC, Pavel-Soloduha commented on Reports/Siniak_Danila/lab2/index.html
> +    <input type="button" value="task1" onclick="task1()">
Введи 13,1 и 13,5

2021-03-14 23:49 UTC, Pavel-Soloduha commented on Reports/Siniak_Danila/lab2/index.html
> +    <input type="button" value="task3" onclick="task3()">
Кажись чего-то не хватает в третьей лабе.

2021-03-14 23:49 UTC, Pavel-Soloduha commented on Reports/Siniak_Danila/lab2/index.html
> +    <input type="button" value="task4" onclick="task4()">
2016 02 31 -> Среда, звучит очень неправильно.

2021-03-15 13:08 UTC, DanilaSiniak commented on Reports/Siniak_Danila/lab2/index.html
> +    <input type="button" value="task1" onclick="task1()">
Всё верно, первое число меньше. 
Верно, потому что парсится во float, (  Number.parseFloat )

2021-03-15 13:08 UTC, DanilaSiniak commented on Reports/Siniak_Danila/lab2/index.html
> +    <input type="button" value="task4" onclick="task4()">
Изменил.

2021-03-15 13:10 UTC, DanilaSiniak commented on Reports/Siniak_Danila/lab2/index.html
> +    <input type="button" value="task3" onclick="task3()">
Перепроверил, всё верно...

2021-03-16 14:38 UTC, Pavel-Soloduha approved these changes

2021-03-16 15:19 UTC, merged