Lab2/kalinovskiy vladimir
lwwwrjke-org/po-4-wt pull request #38
Opened 2021-03-12 19:54 UTC by vovasaxon

2021-03-15 00:16 UTC, Pavel-Soloduha requested changes

2021-03-15 00:16 UTC, Pavel-Soloduha commented on Reports/Kalinovskiy_Vladimir/lab2/index.html
> +<script src='task4.js'></script>
Что-то есть подозрительное в Среде которая выпадает на 2016-02-31

2021-03-17 20:19 UTC, Pavel-Soloduha requested changes

2021-03-17 20:19 UTC, Pavel-Soloduha commented on Reports/Kalinovskiy_Vladimir/lab2/index.html
> +<script src='task1.js'></script>
Сделай кнопки для вызова скриптов

2021-03-17 21:43 UTC, Pavel-Soloduha requested changes
Я видимо неправильно объяснил. Сделай так чтобы когда открывался index.html не выполнялись скрипты заданий. Они должны выполняться после нажатия на кнопку выбранного задания.

2021-03-18 20:49 UTC, vovasaxon commented
Хм, не понимаю, что не так тогда
Я так и реализовал - подключил файлы скриптов и вызывал функции из этих файлов
В итоге скрипты и выполняются только при нажатии кнопки 
@Pavel-Soloduha 
![111](https://user-images.githubusercontent.com/73530000/111695738-76f73c00-8844-11eb-8e19-cc28580e3776.png)
![112](https://user-images.githubusercontent.com/73530000/111695745-79599600-8844-11eb-88f5-c2ae71afd4cd.png)

2021-03-18 21:09 UTC, Pavel-Soloduha approved these changes
Возможно я не почистил локально или не перепулил изменения.

2021-03-18 21:11 UTC, merged