lab2/Galanin_Pavel: pull request (2021.02.23)
lwwwrjke-org/po-4-wt pull request #4
Opened 2021-02-23 05:42 UTC by Pavel-Innokentevich-Galanin

2021-03-02 22:27 UTC, Pavel-Soloduha requested changes

2021-03-02 22:27 UTC, Pavel-Soloduha commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/index.md
> +- [Task 1](task-1) - comparing numbers in an infinite loop
Протестируй 13.3 и 13.6 значения и скажи что на выходе.

2021-03-02 22:27 UTC, Pavel-Soloduha commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/task-2/task-2.js
> +    if (!(1 <= NumOfStoreys && NumOfStoreys <= 25)) {
Это скорее замечания уровня обычно так делают:
переменная которую сравниваниют всегда слева, а константа справа.

2021-03-02 22:27 UTC, Pavel-Soloduha commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/index.md
> +- [Task 3](task-3) - get Fibonacci number
Протестируй 4.4 и скажи что на выходе.

2021-03-02 22:27 UTC, Pavel-Soloduha commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/task-4/task-4.js
> +    if (!(1 <= day && day <= 31)) {
Тоже самое замечание относительно оформления кода
переменная которую сравниваниют всегда слева, а константа справа.

2021-03-02 22:54 UTC, Pavel-Innokentevich-Galanin commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/task-2/task-2.js
> +    if (!(1 <= NumOfStoreys && NumOfStoreys <= 25)) {
Математически удобно записать так:
1 ≤ x ≤ 25

2021-03-02 23:47 UTC, Pavel-Innokentevich-Galanin commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/index.md
> +- [Task 1](task-1) - comparing numbers in an infinite loop
```
The first number is less
(первое число меньше)
13.3 < 13.6
```

2021-03-02 23:48 UTC, Pavel-Innokentevich-Galanin commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/index.md
> +- [Task 1](task-1) - comparing numbers in an infinite loop
```
Second number less
(второе число меньше)
13.6 > 13.3
```

2021-03-02 23:51 UTC, Pavel-Innokentevich-Galanin commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/index.md
> +- [Task 3](task-3) - get Fibonacci number
В комментарии прикреплен листинг разметки Markdown. В этом файле нет кода Java Script

2021-03-02 23:56 UTC, Pavel-Innokentevich-Galanin commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/index.md
> +- [Task 3](task-3) - get Fibonacci number
Fibonacci(4) = 3

2021-03-02 23:59 UTC, Pavel-Innokentevich-Galanin commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/index.md
> +- [Task 3](task-3) - get Fibonacci number
```
Fibonacci(4.4) = 5
```

Fibonacci(4.4) = Fibonacci(3.4) + Fibonacci(2.4) = 3 + 2 = 5
Fibonacci(3.4) = Fibonacci(2.4) + Fibonacci(1.4) = 2 + 1 = 3
Fibonacci(2.4) = Fibonacci(1.4) + Fibonacci(0.4) = 1 + 1 = 2
Fibonacci(1.4) = 1
Fibonacci(0.4) = 1

2021-03-03 00:16 UTC, Pavel-Innokentevich-Galanin commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/task-4/task-4.js
> +    if (!(1 <= day && day <= 31)) {
Математически удобно воспринимаемая запись:
1 ≤ day ≤ 31

2021-03-03 00:18 UTC, Pavel-Innokentevich-Galanin commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/task-2/task-2.js
> +    if (!(1 <= NumOfStoreys && NumOfStoreys <= 25)) {
Поменял в коде стиль на такой:

```
if( константа сравнение число && константа сравнение число ) {

}
```

2021-03-03 00:18 UTC, Pavel-Innokentevich-Galanin commented on Reports/Galanin_Pavel/lab2/_myPublicFolder/task-4/task-4.js
> +    if (!(1 <= day && day <= 31)) {
Поменял в коде стиль на такой:

```
if( константа сравнение число && константа сравнение число ) {

}
```

2021-03-03 06:25 UTC, Pavel-Soloduha approved these changes

2021-03-04 18:21 UTC, merged