lab2/Pivnik_Nikolay
lwwwrjke-org/po-4-wt pull request #50
Opened 2021-03-15 19:35 UTC by chelseanvp

Тоже, что и в первой лабе. Вы уже проверяли, все косяки я исправил.

2021-03-17 20:55 UTC, Pavel-Soloduha requested changes

2021-03-17 20:55 UTC, Pavel-Soloduha commented on Reports/Pivnik_Nikolay/lab2/index.html
> +	<script src = "task1.js"> </script>
Сделай кнопки для вызова заданий.

2021-03-18 20:31 UTC, Pavel-Soloduha requested changes
Скрипт от первого задания не вызывается

2021-03-18 20:39 UTC, chelseanvp commented
сейчас 2 минуты исправлю

2021-03-18 21:17 UTC, Pavel-Soloduha approved these changes

2021-03-18 21:22 UTC, merged