lab1/Sergey_Eliseev: add lab1
lwwwrjke-org/po-4-wt pull request #51
Opened 2021-03-16 12:37 UTC by el1seev

2021-03-17 20:59 UTC, Pavel-Soloduha requested changes

2021-03-17 20:59 UTC, Pavel-Soloduha commented on Reports/Sergey_Eliseev/lab1/web1.html.html
> +                <p><a href="#">ADD FILE</a></p>
А где окно выбора файла?

2021-03-17 20:59 UTC, Pavel-Soloduha commented on Reports/Sergey_Eliseev/lab1/web1.html.html
> +                <p> <input type="text" onfocus="this.value=''" value="Your answer" style="width: 400px;" minlenght=50></p>
Перепровить аттрибуты инпута

2021-03-17 20:59 UTC, Pavel-Soloduha commented
А ну и зачем двойные расширения для файлов?

2021-03-22 06:49 UTC, Pavel-Soloduha requested changes
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/minlength

2021-03-22 11:01 UTC, lwwwr approved these changes

2021-03-22 11:02 UTC, merged