lab1/Lud_Alexey : Make lab1
lwwwrjke-org/po-4-wt pull request #55
Opened 2021-03-16 20:01 UTC by AlexeyLud

2021-03-17 21:09 UTC, Pavel-Soloduha requested changes
![image](https://user-images.githubusercontent.com/5824148/111538796-2fa67800-877e-11eb-8e59-ef7145378acd.png)
Кажись чего-то не хватает.

2021-03-17 21:21 UTC, AlexeyLud commented
![1](https://user-images.githubusercontent.com/72168233/111540150-d3dcee80-877f-11eb-826f-63686f85ed2b.png)
Вы про звездочки(обязательное)?

2021-03-18 20:34 UTC, Pavel-Soloduha requested changes
У меня CSS не подгружается, ни в мозилле, ни в хроме
Ubuntu 20.04 Mozilla 86.0 (64-bit
Ubuntu 20.04 Chrome Version 89.0.4389.90 (Official Build) (64-bit)

2021-03-18 21:24 UTC, AlexeyLud commented
Понял, исправлю

2021-03-22 06:40 UTC, Pavel-Soloduha approved these changes

2021-03-22 10:32 UTC, merged