lab2/Lud_Alexey : Make lab2
lwwwrjke-org/po-4-wt pull request #56
Opened 2021-03-16 20:07 UTC by AlexeyLud

2021-03-17 21:15 UTC, Pavel-Soloduha requested changes
Сделай вызов заданий через кнопки, а не через <script/>

2021-03-17 21:15 UTC, Pavel-Soloduha commented on Reports/Lud_Alexey/lab2/ind.html
> +<script src="2lab(1).js"></script>
Введи 12 и 5

2021-03-17 21:15 UTC, Pavel-Soloduha commented on Reports/Lud_Alexey/lab2/ind.html
> +<script src="2lab(2).js"></script>
Неправильно считает, введи 2 2 2.

2021-03-17 21:27 UTC, AlexeyLud commented on Reports/Lud_Alexey/lab2/ind.html
> +<script src="2lab(2).js"></script>
![2](https://user-images.githubusercontent.com/72168233/111540788-a3498480-8780-11eb-8cdf-24f7f9a4ba64.png)
Оно что то не так считает?

2021-03-18 20:38 UTC, Pavel-Soloduha requested changes
>этажность (1-25), число подъездов (1-10), количество квартир на лестничной площадке (1-20). 

Ты неправильно понял задание и соответственно сделал нето что надо.
При вводе 2 2 2 - должно быть 8 квартир, а не 2.

2021-03-18 21:23 UTC, AlexeyLud commented
А, понял, сейчас исправлю

2021-03-22 06:42 UTC, Pavel-Soloduha approved these changes

2021-03-22 10:33 UTC, merged