lab1/Ivanenko_Ivan
lwwwrjke-org/po-4-wt pull request #6
Opened 2021-02-23 11:12 UTC by vangaru

2021-03-02 22:34 UTC, Pavel-Soloduha requested changes

2021-03-02 22:34 UTC, Pavel-Soloduha commented on Reports/Ivanenko_Ivan/lab1/index.html
> +						<input type="text" id="password" name="password" required/>
Где приглашение для ввода текста как в лабе?

2021-03-02 22:34 UTC, Pavel-Soloduha commented on Reports/Ivanenko_Ivan/lab1/index.html
> +						<input type="datetime-local" id="date" name="date" required/>
Хотелось бы увидеть нормальный календарь, а не просто ввод текста

2021-03-03 21:44 UTC, vangaru commented on Reports/Ivanenko_Ivan/lab1/index.html
> +						<input type="text" id="password" name="password" required/>
вы про placeholder?

2021-03-03 21:48 UTC, Pavel-Soloduha commented on Reports/Ivanenko_Ivan/lab1/index.html
> +						<input type="text" id="password" name="password" required/>
Да.

2021-03-04 06:08 UTC, vangaru commented on Reports/Ivanenko_Ivan/lab1/index.html
> +						<input type="datetime-local" id="date" name="date" required/>
а что не так с календарем? input type=datetime-local создает календарь. Да, можно вводить текст, но в форме есть иконка, по нажатию которой появляется календарь

2021-03-04 08:23 UTC, Pavel-Soloduha commented on Reports/Ivanenko_Ivan/lab1/index.html
> +						<input type="datetime-local" id="date" name="date" required/>
![image](https://user-images.githubusercontent.com/5824148/109933009-fe3c9f80-7cdb-11eb-83f1-1dc2da093577.png)
Ubuntu 20.04 Firefox 86.0 - ничего не вижу вот и спрашиваю.

2021-03-04 08:34 UTC, vangaru commented on Reports/Ivanenko_Ivan/lab1/index.html
> +						<input type="datetime-local" id="date" name="date" required/>
Если использовать браузер mozilla firefox, то datetime-local работать не будет, т.к. он там не поддерживается

2021-03-04 08:42 UTC, Pavel-Soloduha commented on Reports/Ivanenko_Ivan/lab1/index.html
> +						<input type="datetime-local" id="date" name="date" required/>
Я конечно понимаю, что Хром победил и у Мозилы маленький процент, но ИМХО лучше делать более кроссплатформенное, а не Хромозаточенное. @lwwwr проверь пожалуйста на Safari и вынеси вердикт надо ли переделывать или это достаточное решение.

2021-03-04 08:50 UTC, lwwwr commented on Reports/Ivanenko_Ivan/lab1/index.html
> +						<input type="datetime-local" id="date" name="date" required/>
В safari тоже не работает
![image](https://user-images.githubusercontent.com/22084636/109937083-a869f680-7cdf-11eb-9494-88bb057a1143.png)

Давайте-ка запилим и под firefox, и под safari
если будет работать под firefox, то будет и под safari
cc: @vangaru @Pavel-Soloduha

2021-03-04 08:51 UTC, vangaru commented on Reports/Ivanenko_Ivan/lab1/index.html
> +						<input type="datetime-local" id="date" name="date" required/>
И шрифты не работают(((

2021-03-04 09:09 UTC, vangaru commented on Reports/Ivanenko_Ivan/lab1/index.html
> +						<input type="datetime-local" id="date" name="date" required/>
поменял datetine-local на date

2021-03-04 21:05 UTC, Pavel-Soloduha approved these changes

2021-03-04 21:10 UTC, merged