lab3
lwwwrjke-org/po-4-wt pull request #66
Opened 2021-03-20 21:38 UTC by chelseanvp

2021-03-22 20:31 UTC, Pavel-Soloduha requested changes
[-6, 2, -1] и [2, 5, -1] - должно возвращать ошибку
[5, 2, -1] - должно вернуть [5, 4, 3, 2]

2021-03-22 22:42 UTC, chelseanvp commented
Я думал что первый аргумент это левая граница, второй – правая граница массива. И если шаг положительный, то мы двигаемся от левого к правому, а если отрицательный – от правого к левому.. А как надо?

2021-03-28 12:28 UTC, chelseanvp commented
1е задание работает как надо.

2021-03-30 02:24 UTC, Pavel-Soloduha approved these changes

2021-03-30 05:28 UTC, merged