Lab4/Mayeski_Aliaksandr
lwwwrjke-org/po-4-wt pull request #69
Opened 2021-03-21 12:29 UTC by GroD-off

2021-03-23 14:48 UTC, Pavel-Soloduha commented
PR надо направлять в свою ветку, а не main

2021-03-23 14:48 UTC, Pavel-Soloduha requested changes
PR надо направлять в свою ветку, а не main

2021-03-23 18:40 UTC, lwwwr requested changes
![image](https://user-images.githubusercontent.com/22084636/112200426-45091f80-8c20-11eb-96f3-4047af8fa46c.png)
то, что апи-колы работают - это хорошо. но возьми ты заюзай какой бутстраповский темплейт и сделай красивую страницу

2021-03-30 01:52 UTC, Pavel-Soloduha approved these changes

2021-03-30 07:41 UTC, merged