Lab4/lud alexey
lwwwrjke-org/po-4-wt pull request #78
Opened 2021-03-24 19:25 UTC by AlexeyLud

2021-03-30 01:55 UTC, Pavel-Soloduha requested changes
![image](https://user-images.githubusercontent.com/5824148/112921774-0984be80-9114-11eb-830b-22effd2cda29.png)
![image](https://user-images.githubusercontent.com/5824148/112921835-24573300-9114-11eb-9e7d-9134aa263f44.png)

2021-03-30 16:21 UTC, AlexeyLud commented
Протите, забыл про сервер сказать

2021-04-05 07:03 UTC, Pavel-Soloduha approved these changes
В следующих раз буду ОЧЕНЬ сильно негодовать если не будет чего-то от Docker\docker-compose. А то руками собирать и запускать - такое себе.

Dockerfile

>FROM nginx:alpine
>WORKDIR /usr/share/nginx/html
>COPY ./ ./
>EXPOSE 80

2021-04-05 07:14 UTC, merged

2021-04-05 07:15 UTC, AlexeyLud commented
Понял, исправлюсь