Lab1_wt - Gribovskij_Dima
lwwwrjke-org/po-4-wt pull request #8
Opened 2021-02-23 17:24 UTC by NeitLC

2021-03-02 22:40 UTC, Pavel-Soloduha requested changes

2021-03-02 22:40 UTC, Pavel-Soloduha commented on Reports/Gribovskij_Dima/lab1/index.html
> +                    <input type="text" id="text1" class="form-control" placeholder="Your answer" maxlength="50" style="width: 95%;">
Близко, но нет. В тексте ведь написано про минимум 50 символов, а не максимум.

2021-03-04 10:34 UTC, NeitLC commented on Reports/Gribovskij_Dima/lab1/index.html
> +                    <input type="text" id="text1" class="form-control" placeholder="Your answer" maxlength="50" style="width: 95%;">
Исправил maxlength на minlength

2021-03-04 14:17 UTC, Pavel-Soloduha approved these changes

2021-03-04 19:29 UTC, merged