Lab5/Mayeski_Aliaksandr
lwwwrjke-org/po-4-wt pull request #97
Opened 2021-04-11 11:28 UTC by GroD-off

2021-04-20 12:11 UTC, Pavel-Soloduha requested changes
![image](https://user-images.githubusercontent.com/5824148/115393557-8292a580-a1ea-11eb-8f73-40310838633f.png)
не завелось на npm 7.7.6, после npm ci, npm start

2021-04-20 13:04 UTC, GroD-off commented
> ![image](https://user-images.githubusercontent.com/5824148/115393557-8292a580-a1ea-11eb-8f73-40310838633f.png)
> не завелось на npm 7.7.6, после npm ci, npm start

Их надо дополнительно докачивать через npm i @fortawesome/free-solid-svg-icons

2021-04-20 13:07 UTC, Pavel-Soloduha commented
> > ![image](https://user-images.githubusercontent.com/5824148/115393557-8292a580-a1ea-11eb-8f73-40310838633f.png)
> > не завелось на npm 7.7.6, после npm ci, npm start
> 
> Их надо дополнительно докачивать через npm i @fortawesome/free-solid-svg-icons

А слабо было сразу в README написать или в package.json пихнуть?

2021-04-20 14:26 UTC, Pavel-Soloduha commented
npm ci && \
npm i @fortawesome/fontawesome-svg-core && \
npm i @fortawesome/react-fontawesome && \
npm i @fortawesome/free-solid-svg-icons

![image](https://user-images.githubusercontent.com/5824148/115412958-7a903100-a1fd-11eb-94cb-ce5f37447171.png)

Продолжаем разговор

2021-04-20 14:31 UTC, Pavel-Soloduha requested changes
1

2021-04-20 14:35 UTC, GroD-off commented
> npm ci &&
> npm i @fortawesome/fontawesome-svg-core &&
> npm i @fortawesome/react-fontawesome &&
> npm i @fortawesome/free-solid-svg-icons
> 
> ![image](https://user-images.githubusercontent.com/5824148/115412958-7a903100-a1fd-11eb-94cb-ce5f37447171.png)
> 
> Продолжаем разговор

я уже понял, что зря я это докачивал, лучше бы ссылку использовал, но всё же npm install bootstrap

2021-05-13 19:25 UTC, Pavel-Soloduha approved these changes

2021-05-13 21:20 UTC, merged